---
title: "flat for basic glosmurb functions"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
study_areas=sf::st_read("../collect_OSM_gloUrb/data/study_areas_temp/study_areas_20230713_buffer.shp")
```

```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_full_1.Rmd", vignette_name = "Get started")
```
  


<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
library(tidyverse)
library(osmdata) 
library(sf) 
library(leaflet)
```


# Include some data examples in your package


```{r development-dataset}
# Run all this chunk in the console directly
# There already is a dataset in the "inst/" directory
# Make the dataset file available to the current Rmd during development
pkgload::load_all(path = here::here(), export_all = FALSE)

# You will be able to read your example data file in each of your function examples and tests as follows - see chunks below
data(confluence)
```

```{r function-confluence}
#' confluence
#'
#' A bounding shape corresponding to the confluence of the Rhone and Saone rivers in Lyon, France.
#'
#' @format An sf object corresponding to a bounding box
"confluence"
```



# Get all OSM key-value objects inside shape

Based on a key-value (as listed [here](https://wiki.openstreetmap.org/wiki/Map_features)) and bounding shape, this function collects all OSM objects (all geometries).

```{r function-get_osmdata}
#' collect OSM data corresponding to a key-value inside a bounding shape. If a file already exists corresponding to "{dir_name}/{shape_name}_{key}_{value}, the data is not retrieved through a new query but through reading this file.
#' @param key OSM key
#' @param value OSM value
#' @param shape_name shape (sf object) or name of a shape (inside quotes), corresponding to the geographical area inside which to look for key-value occurrences
#' @param save if TRUE, the data is saved locally in directory dir_name, with name {key}_{value}.RDS. If the file already exists nothing is done. Defaults to FALSE. If 
#' @param dir_name the directory under which returned data is saved. Defaults to "data/osmdata".
#' @param return whether the object should be returned (could be FALSE when save is TRUE)
#' @return a list with elements key, value, shape_name and result which is an osmdata_sf object
#' @export
#'
#' @examples
get_osmdata=function(key, value, shape_name,return=TRUE, save=FALSE, dir_name="data/osmdata"){
  osmdata_file=glue::glue("{dir_name}/{shape_name}/{key}-{value}.RDS")
  if(file.exists(osmdata_file)){
      if(return){
        result=readRDS(osmdata_file)
        return(result)
      }
      if(!return){
        return("Done already")
      }
  }
  if(is.character(shape_name)){
    shape=get(shape_name)
  }else{
    shape=shape_name
    shape_name=as.character(substitute(shape_name))
  }
  bbox=sf::st_coordinates(shape)[,1:2]
  result=osmdata::opq(bbox = bbox, timeout=120)%>%
    osmdata::add_osm_feature(key = key,
                             value = value) %>% 
    osmdata::osmdata_sf()

  for(type in c("osm_points",
                "osm_lines",
                "osm_polygons",
                "osm_multilines",
                "osm_multipolygons")){
    if(!is.null(result[[type]])){
      shape_osm=sf::st_make_valid(result[[type]])
      sf::st_agr(shape_osm)="constant"
      # removes warnings that attributes are considered constant throughout multiple geometries
      result[[type]]=sf::st_intersection(shape_osm,shape)
      if(nrow(result[[type]])==0){result[type]=list(NULL)} 
      # rather than result[[type]]=NULL which removes element
    }
  }
  result=list(key=key,
              value=value,
              shape_name=shape_name,
              result=result)
  if(save){
      if(!dir.exists(glue::glue("{dir_name}/{shape_name}"))){
        dir.create(glue::glue("{dir_name}/{shape_name}"),
                   recursive=TRUE)
      }
      if(!file.exists(osmdata_file)){
          saveRDS(result,osmdata_file)
      }
  }
  return(result)
}
```

```{r examples-get_osmdata}
data(confluence)
bridges_confluence=get_osmdata("man_made","bridge","confluence") 
bridges_confluence=get_osmdata("man_made","bridge","confluence", save=TRUE)
drinking_water_confluence=get_osmdata("amenity","drinking_water","confluence",save=TRUE)
landuse_vineyard_condrieu=get_osmdata("landuse","vineyard","condrieu")
landuse_port_lyon=get_osmdata("landuse","port","lyon")
```


```{r tests}
test_that("get_osmdata returns a correctly structured list for a simple query", {
  bridges_confluence=get_osmdata("man_made","bridge","confluence")
  expect_true(class(bridges_confluence)=="list")
  expect_true("osmdata" %in% class(bridges_confluence$result)) 
})
test_that("get_osmdata returns NULL parts rather than sf objects with 0 rows", {
  landuse_port_lyon=get_osmdata("landuse","port","lyon")
  expect_true(is.null(landuse_port_lyon$result$osm_points))
})
```

# clear_osmdata
    
```{r function-clear_osmdata}
#' Clears the local {dir_name}/{shape_name}/{key}_{value}.RDS file if it exists
#' @param key OSM key
#' @param value OSM value
#' @param shape_name shape (sf object) or name of a shape (inside quotes), corresponding to the geographical area inside which to look for key-value occurrences
#' @param dir_name the directory under which returned data is saved. Defaults to "data/osmdata".
#' @export
clear_osmdata <- function(key,value,shape_name,dir_name="data/osmdata"){
  osmdata_file=glue::glue("{dir_name}/{shape_name}/{key}-{value}.RDS")
  result="does not exist"
  if(file.exists(osmdata_file)){
    done=file.remove(osmdata_file)
    result="removed"
  }
  return(result)
}
```
  
```{r example-clear_osmdata}
bridges_confluence=get_osmdata("man_made","bridge","confluence", save=TRUE)
file.exists("data/osmdata/confluence/man_made-bridge.RDS")
clear_osmdata("man_made","bridge","confluence")
file.exists("data/osmdata/confluence/man_made-bridge.RDS")
```
  
```{r tests-clear_osmdata}
test_that("clear_osmdata works", {
  expect_true(inherits(clear_osmdata, "function")) 
})
```
  
  
# Pick OSM data (according to geometry)

OSM data might correspond to varying geometries (points, lines, polygons, etc.). 

```{r function-pick_osmdata}
#' Pick the information corresponding to a certain geometry
#' @param osmdata the result returned by get_osmdata
#' @param label the label letting the user know the type of object
#' @param geom the type of geometry. Can be for instance "osm_points","osm_lines","osm_polygons"

#' @return an sf object
#' 
#' @export
pick_osmdata=function(osmdata, geom="osm_points", label=NA){
  if(is.na(label)){label=osmdata$value}
  
  layer=osmdata$result[[geom]] 
  if(!is.null(layer)){
    layer=layer %>%  
      dplyr::mutate(label=label)
  }
  multitype=stringr::str_replace(geom,"osm_","osm_multi")
  layer2=osmdata$result[[multitype]] 
  if(!is.null(layer2)){
    
    layer2=layer2 %>%  
      dplyr::mutate(label=label)
    cols_in_common=colnames(layer2)[which(colnames(layer2) %in% colnames(layer))]
    layer2=layer2[,cols_in_common]
    layer =layer [,cols_in_common]
    if(is.null(layer)){
    layer=layer2
    }
    if(!is.null(layer) & !is.null(layer2)){
      layer=rbind(layer,layer2)
    }
  }

  return(layer)
}
```
  
```{r example-pick_osmdata}
bridges_confluence=get_osmdata("man_made","bridge",confluence) 
plg_bridges_confluence=pick_osmdata(bridges_confluence,
                                    geom="osm_polygons")
water_confluence=get_osmdata("natural","water",confluence)
plg_water_confluence=pick_osmdata(water_confluence,
                                  geom="osm_polygons")
```
  
```{r tests-pick_osmdata}
test_that("pick_osmdata returns a correctly structured list for a simple query", {
  bridges_confluence=get_osmdata("man_made","bridge",confluence) 
  plg_bridges_confluence=pick_osmdata(bridges_confluence,
                                      geom="osm_polygons")
  expect_true("sf" %in% class(plg_bridges_confluence))
}) 
```
