# WARNING - Generated by {fusen} from dev/flat_1.Rmd: do not edit by hand

test_that("get_osmdata returns a correctly structured list for a simple query", {
  bridges_confluence=get_osmdata("man_made","bridge","confluence")
  expect_true(class(bridges_confluence)=="list")
  expect_true("osmdata" %in% class(bridges_confluence$result)) 
})
test_that("get_osmdata returns NULL parts rather than sf objects with 0 rows", {
  landuse_port_lyon=get_osmdata("landuse","port","lyon")
  expect_true(is.null(landuse_port_lyon$result$osm_points))
})
