# WARNING - Generated by {fusen} from dev/flat_1.Rmd: do not edit by hand

test_that("pick_osmdata returns a correctly structured list for a simple query", {
  bridges_confluence=get_osmdata("man_made","bridge",confluence) 
  plg_bridges_confluence=pick_osmdata(bridges_confluence,
                                      geom="osm_polygons")
  expect_true("sf" %in% class(plg_bridges_confluence))
}) 
