# WARNING - Generated by {fusen} from dev/flat_2.Rmd: do not edit by hand

#' Builds basic leaflet map based on study area (shape)
#' @param shape the study area which should be displayed by the map
#' @return a leaflet map
#' @export
#' @examples
#' data(confluence)
#' base_map("confluence")
base_map <- function(shape_name){
  if(is.character(shape_name)){
    shape=get(shape_name)
  }else{
    shape=shape_name
    shape_name=as.character(substitute(shape_name))
  }
  map=leaflet::leaflet(shape) %>% 
      leaflet::addTiles(group = "OSM map") %>% 
      leaflet::addPolygons(data=shape,col="red")
  return(map)
}
