# WARNING - Generated by {fusen} from dev/flat_2.Rmd: do not edit by hand

#' Creates an html column detailing information regarding OSM items
#' @param gosmdata the gosmdata element you wish to detail
#' @return gosmdata with additional detail column
#' 
#' @export
#' @examples
#' g_parks=get_osmdata("leisure","park","confluence") %>% 
#'   pick_osmdata(geom="osm_polygons") %>% 
#'   detail_element()
#' g_parks
detail_element <- function(gosmdata){
  if(is.null(gosmdata)){return(NULL)}
  flink=function(wikidata){
    wikidata_root="https://www.wikidata.org/wiki/"
    if(!is.na(wikidata)){
        wikidata_link=glue::glue("<p><a href='{wikidata_root}{wikidata}' target='_blank'>Wikidata</a></p>")}else{
        wikidata_link=""
        }
  return(wikidata_link)
  }
  gosmdata=gosmdata %>% 
    dplyr::mutate(detail="")
  if("name" %in% names(gosmdata)){
      gosmdata=gosmdata %>% 
        dplyr::mutate(detail=dplyr::case_when(is.na(name)~detail,
                                              !is.na(name)~glue::glue("{detail}<h2>{name}</h2>"))) 
  }
  if("wikidata" %in% names(gosmdata)){
    wikidata_link=purrr::map_chr(gosmdata$wikidata, flink)
      gosmdata=gosmdata %>% 
        dplyr::mutate(detail=glue::glue("{detail}{wikidata_link}")) 
  }
  gosmdata=gosmdata %>% 
    dplyr::mutate(detail=dplyr::case_when(detail==""~NA_character_,
                                          detail!=""~glue::glue("<html>{detail}</html>")))
                
  return(gosmdata)
    
}
