# WARNING - Generated by {fusen} from dev/flat_1.Rmd: do not edit by hand

#' collect OSM data corresponding to a key-value inside a bounding shape. If a file already exists corresponding to "{dir_name}/{shape_name}_{key}_{value}, the data is not retrieved through a new query but through reading this file.
#' @param key OSM key
#' @param value OSM value
#' @param shape_name shape (sf object) or name of a shape (inside quotes), corresponding to the geographical area inside which to look for key-value occurrences
#' @param save if TRUE, the data is saved locally in directory dir_name, with name {key}_{value}.RDS. If the file already exists nothing is done. Defaults to FALSE. If 
#' @param dir_name the directory under which returned data is saved. Defaults to "data/osmdata".
#' @param return whether the object should be returned (could be FALSE when save is TRUE)
#' @return a list with elements key, value, shape_name and result which is an osmdata_sf object
#' @export
#'
#' @examples
#' data(confluence)
#' bridges_confluence=get_osmdata("man_made","bridge","confluence") 
#' bridges_confluence=get_osmdata("man_made","bridge","confluence", save=TRUE)
#' drinking_water_confluence=get_osmdata("amenity","drinking_water","confluence",save=TRUE)
#' landuse_vineyard_condrieu=get_osmdata("landuse","vineyard","condrieu")
#' landuse_port_lyon=get_osmdata("landuse","port","lyon")
get_osmdata=function(key, value, shape_name,return=TRUE, save=FALSE, dir_name="data/osmdata"){
  osmdata_file=glue::glue("{dir_name}/{shape_name}/{key}-{value}.RDS")
  if(file.exists(osmdata_file)){
      if(return){
        result=readRDS(osmdata_file)
        return(result)
      }
      if(!return){
        return("Done already")
      }
  }
  if(is.character(shape_name)){
    shape=get(shape_name)
  }else{
    shape=shape_name
    shape_name=as.character(substitute(shape_name))
  }
  bbox=sf::st_coordinates(shape)[,1:2]
  result=osmdata::opq(bbox = bbox, timeout=120)%>%
    osmdata::add_osm_feature(key = key,
                             value = value) %>% 
    osmdata::osmdata_sf()

  for(type in c("osm_points",
                "osm_lines",
                "osm_polygons",
                "osm_multilines",
                "osm_multipolygons")){
    if(!is.null(result[[type]])){
      shape_osm=sf::st_make_valid(result[[type]])
      sf::st_agr(shape_osm)="constant"
      # removes warnings that attributes are considered constant throughout multiple geometries
      result[[type]]=sf::st_intersection(shape_osm,shape)
      if(nrow(result[[type]])==0){result[type]=list(NULL)} 
      # rather than result[[type]]=NULL which removes element
    }
  }
  result=list(key=key,
              value=value,
              shape_name=shape_name,
              result=result)
  if(save){
      if(!dir.exists(glue::glue("{dir_name}/{shape_name}"))){
        dir.create(glue::glue("{dir_name}/{shape_name}"),
                   recursive=TRUE)
      }
      if(!file.exists(osmdata_file)){
          saveRDS(result,osmdata_file)
      }
  }
  return(result)
}
