# WARNING - Generated by {fusen} from dev/flat_1.Rmd: do not edit by hand

#' confluence
#'
#' A bounding shape corresponding to the confluence of the Rhone and Saone rivers in Lyon, France.
#'
#' @format An sf object corresponding to a bounding box
"confluence"
