# WARNING - Generated by {fusen} from dev/flat_1.Rmd: do not edit by hand

#' Pick the information corresponding to a certain geometry
#' @param osmdata the result returned by get_osmdata
#' @param label the label letting the user know the type of object
#' @param geom the type of geometry. Can be for instance "osm_points","osm_lines","osm_polygons"

#' @return an sf object
#' 
#' @export
#' @examples
#' bridges_confluence=get_osmdata("man_made","bridge",confluence) 
#' plg_bridges_confluence=pick_osmdata(bridges_confluence,
#'                                     geom="osm_polygons")
#' water_confluence=get_osmdata("natural","water",confluence)
#' plg_water_confluence=pick_osmdata(water_confluence,
#'                                   geom="osm_polygons")
pick_osmdata=function(osmdata, geom="osm_points", label=NA){
  if(is.na(label)){label=osmdata$value}
  
  layer=osmdata$result[[geom]] 
  if(!is.null(layer)){
    layer=layer %>%  
      dplyr::mutate(label=label)
  }
  multitype=stringr::str_replace(geom,"osm_","osm_multi")
  layer2=osmdata$result[[multitype]] 
  if(!is.null(layer2)){
    
    layer2=layer2 %>%  
      dplyr::mutate(label=label)
    cols_in_common=colnames(layer2)[which(colnames(layer2) %in% colnames(layer))]
    layer2=layer2[,cols_in_common]
    layer =layer [,cols_in_common]
    if(is.null(layer)){
    layer=layer2
    }
    if(!is.null(layer) & !is.null(layer2)){
      layer=rbind(layer,layer2)
    }
  }

  return(layer)
}
